const sampleSneakerData = {
  products: [
    {
      name: "Nike Air Max 270",
      slug: "nike-air-max-270",
      category: "Men's Sneakers",
      description:
        "Breathable mesh design with responsive cushioning for all-day comfort.",
      images: [
        "/images/sample-sneakers/nike-air-max-270-1.jpg",
        "/images/sample-sneakers/nike-air-max-270-2.jpg",
      ],
      price: 129.99,
      brand: "Nike",
      rating: 4.8,
      numReviews: 25,
      stock: 12,
      isFeatured: true,
      banner: "banner-air-max-270.jpg",
    },
    {
      name: "Adidas Ultraboost 22",
      slug: "adidas-ultraboost-22",
      category: "Men's Sneakers",
      description:
        "High-performance running shoes with an adaptive fit and energy return.",
      images: [
        "/images/sample-sneakers/adidas-ultraboost-22-1.jpg",
        "/images/sample-sneakers/adidas-ultraboost-22-2.jpg",
      ],
      price: 159.95,
      brand: "Adidas",
      rating: 4.7,
      numReviews: 18,
      stock: 10,
      isFeatured: true,
      banner: "banner-ultraboost-22.jpg",
    },
    {
      name: "Puma RS-X³ Puzzle",
      slug: "puma-rs-x3-puzzle",
      category: "Men's Sneakers",
      description: "Bold and colorful sneakers with retro-inspired design.",
      images: [
        "/images/sample-sneakers/puma-rs-x3-1.jpg",
        "/images/sample-sneakers/puma-rs-x3-2.jpg",
      ],
      price: 109.99,
      brand: "Puma",
      rating: 4.4,
      numReviews: 12,
      stock: 8,
      isFeatured: false,
      banner: null,
    },

    {
      name: "Vans Old Skool",
      slug: "vans-old-skool",
      category: "Men's Sneakers",
      description: "Classic skate shoes with durable suede and canvas uppers.",
      images: [
        "/images/sample-sneakers/vans-old-skool-1.jpg",
        "/images/sample-sneakers/vans-old-skool-2.jpg",
      ],
      price: 75.0,
      brand: "Vans",
      rating: 4.6,
      numReviews: 22,
      stock: 9,
      isFeatured: false,
      banner: null,
    },
    {
      name: "New Balance 574",
      slug: "new-balance-574",
      category: "Men's Sneakers",
      description:
        "Versatile sneakers with heritage-inspired design and comfort.",
      images: [
        "/images/sample-sneakers/new-balance-574-1.jpg",
        "/images/sample-sneakers/new-balance-574-2.jpg",
      ],
      price: 89.99,
      brand: "New Balance",
      rating: 4.5,
      numReviews: 15,
      stock: 7,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Jordan Retro 1 High OG",
      slug: "jordan-retro-1-high-og",
      category: "Men's Sneakers",
      description:
        "Iconic basketball sneakers with premium leather and classic design.",
      images: [
        "/images/sample-sneakers/jordan-retro-1-1.jpg",
        "/images/sample-sneakers/jordan-retro-1-2.jpg",
      ],
      price: 170.0,
      brand: "Jordan",
      rating: 4.9,
      numReviews: 40,
      stock: 5,
      isFeatured: true,
      banner: "banner-jordan-retro-1.jpg",
    },
    {
      name: "Reebok Club C 85",
      slug: "reebok-club-c-85",
      category: "Men's Sneakers",
      description: "Clean and minimalist sneakers with soft leather upper.",
      images: [
        "/images/sample-sneakers/reebok-club-c-85-1.jpg",
        "/images/sample-sneakers/reebok-club-c-85-2.jpg",
      ],
      price: 75.99,
      brand: "Reebok",
      rating: 4.3,
      numReviews: 10,
      stock: 11,
      isFeatured: false,
      banner: null,
    },
  ],
};

export default sampleSneakerData;
